### ISSUE TITLE
Exception on Generate Tests

### ISSUE THREAD

**Issue by mklierman** [mattwhitfield/unittestgenerator#2]
Anytime I try to generate tests, whether it be at a project level, class level, or method level, I get this exception. 

---------------------------
Microsoft Visual Studio
---------------------------
Unitverse

Exception raised
System.MissingMethodException: Method not found: 'EnvDTE.Solution EnvDTE._DTE.get_Solution()'.

   at Unitverse.Helper.ProjectItemModel.get_TargetProject()

   at Unitverse.Commands.GenerateUnitTestsCommand.<>c__DisplayClass12_0.<Execute>b__0() in D:\a\unittestgenerator\unittestgenerator\src\Unitverse\Commands\GenerateUnitTestsCommand.cs:line 135

   at Unitverse.Helper.Attempt.Action(Action action, IUnitTestGeneratorPackage package) in D:\a\unittestgenerator\unittestgenerator\src\Unitverse\Helper\Attempt.cs:line 21
---------------------------
OK   
---------------------------

I am using VS2022 and the extension version is 0.67.0.0

**Comment by mattwhitfield** [comment]
Hello - thanks for reporting the issue. I'd actually noticed this and fixed it (if you see the other issue in this repo).

Unfortunately, due to the way that VS2022 is 64-bit - there isn't a way to make the same extension work for both VS2019 and VS2022. So I had to split the extension in two - one for 2019 and one for 2022. You should be able to find the VS2022 extension here: https://marketplace.visualstudio.com/items?itemName=MattWhitfield.UnitverseVS2022

Please let me know if that doesn't resolve the issue for you 👍

**Comment by mattwhitfield** [comment]
I'm going to close this now, since it's been a while. Please do feel free to re-open if the issue remains for you
