### ISSUE TITLE
Delegates with out parameter not generated correctly

### ISSUE THREAD

**Issue by CoenraadS** [mattwhitfield/unittestgenerator#52]
Hi again :)

Input:  
```
public delegate void ExpandConstantDelegate(string input, out string output);
public static void RegisterExpandConstantCallback(ExpandConstantDelegate callback)
{
}
```

Generated test

```
 [Test]
        public static void CanCallRegisterExpandConstantCallback()
        {
            // Arrange
            Exports.ExpandConstantDelegate callback = (x, y) => { };
                                                          ^ Should have out keyword   
            // Act
            Exports.RegisterExpandConstantCallback(callback);
            
            // Assert
            Assert.Fail("Create or modify test");
        }
```

Easy to manually fix, just thought I would report it

**Comment by mattwhitfield** [comment]
Fixed in 0.99 - have added a bunch of those sorts of cases to the delegate example (https://unitverse.readthedocs.io/en/latest/examples/DelegateGeneration/)

FWIW, It may be an easy fix - but one of the main goals with Unitverse is to make it emit code that compiles for the vast majority of tests. So even though it's small, please do feel free to open issues for this sort of stuff.

Thanks for the report 👍
